name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [master, main]

jobs:
  deploy:
    runs-on: self-hosted
    
    permissions:
      contents: write
      pull-requests: write
      checks: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build with Nix
        run: |
          echo "Building test-app..."
          nix build .#test-app
          echo "Store path: $(readlink result)"
      
      - name: Deploy to production
        if: success()
        run: |
          echo "Updating nix profile..."
          nix profile remove test-app 2>/dev/null || true
          nix profile install .#test-app
          
          echo "Restarting service using polkit (no sudo needed)..."
          systemctl restart test-app
          
          echo "Checking service status..."
          systemctl status test-app --no-pager || true
          
          echo "Testing endpoint..."
          sleep 2
          EMOJI=$(curl -s http://localhost:3001 | grep -o "emoji.*</div>" | head -1)
          echo "Current emoji: $EMOJI"
          
          # Verify deployment succeeded
          if [[ -z "$EMOJI" ]]; then
            echo "Failed to fetch page!"
            exit 1
          fi
      
      - name: Auto-merge PR
        if: |
          success() && 
          github.event_name == 'pull_request' && 
          github.event.pull_request.user.login == github.repository_owner
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "All tests and deployment passed! Merging PR #${{ github.event.pull_request.number }}"
          gh pr merge ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --squash \
            --delete-branch