name: CI

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build with Nix
        run: |
          echo "Building test-app..."
          nix build .#test-app
          echo "Store path: $(readlink result)"
      
      - name: Deploy to production
        run: |
          echo "Updating nix profile..."
          nix profile remove test-app 2>/dev/null || true
          nix profile install .#test-app
          
          echo "Restarting service using polkit (no sudo needed)..."
          systemctl restart test-app
          
          echo "Checking service status..."
          systemctl status test-app --no-pager || true
          
          echo "Testing endpoint..."
          sleep 2
          curl -s http://localhost:3001 | grep -o "emoji.*</div>" | head -1 || echo "Could not fetch page"