name: CI

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build with Nix
        run: |
          echo "Building test-app..."
          nix build .#test-app
          echo "Store path: $(readlink result)"
      
      - name: Deploy to production
        run: |
          echo "Updating nix profile..."
          nix profile remove test-app 2>/dev/null || true
          nix profile install .#test-app
          
          echo "Restarting service..."
          # Try with sudo first (if available and configured)
          if command -v sudo &> /dev/null; then
            echo "Using sudo to restart service..."
            sudo systemctl restart test-app
          else
            echo "Sudo not available, trying direct systemctl..."
            /run/current-system/sw/bin/systemctl restart test-app || systemctl restart test-app
          fi
          
          echo "Checking service status..."
          systemctl status test-app --no-pager || true
          
          echo "Testing endpoint..."
          sleep 2
          curl -s http://localhost:3001 | grep -o "emoji.*</div>" | head -1 || echo "Could not fetch page"